#!/usr/bin/python

import os
import subprocess
import sys
import tempfile

repository = os.getcwd()
integration_dir = tempfile.mkdtemp()

def run_and_exit_on_error(command):
    return_code = subprocess.call(command, shell=True)
    if return_code:
        exit(1)


run_and_exit_on_error("git clone %s %s" % (repository, integration_dir))

os.chdir(integration_dir)

try:
    subprocess.check_output("./run_integration_tests")
    run_and_exit_on_error("./promote_to_live")
except subprocess.CalledProcessError, e:
    process = subprocess.Popen("./handle_integration_error", stdin=subprocess.PIPE)
    process.communicate(e.output)
